name: Build and Push to ECR (All Branches)

on:
  push:
    branches:
      - '**'  # trigger on push to any branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
      ECR_URI: ${{ secrets.ECR_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO_NAME:latest -f ./app/Dockerfile ./app

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPO_NAME:latest $ECR_URI:latest

      - name: Push to Amazon ECR
        run: |
          docker push $ECR_URI:latest
